language: cpp
before_script:
- sudo apt-get update -q
- sudo apt-get install s3cmd grep zip mailutils
- sudo apt-get install libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386
- sudo apt-get install python-serial python-argparse
- sudo apt-get install flex bison libncurses5-dev autoconf texinfo build-essential
  libtool zlib1g-dev genromfs git wget
- sudo apt-get install gcc-avr
- pushd .
- cd ~
- wget https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
- tar -jxf gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
- exportline="export PATH=$HOME/gcc-arm-none-eabi-4_9-2014q4/bin:\$PATH"
- if grep -Fxq "$exportline" ~/.profile; then echo nothing to do ; else echo $exportline >> ~/.profile; fi
- . ~/.profile
- popd
- wget --quiet --timestamping https://sourceforge.net/projects/pinguinoide/files/linux/pinguino-linux64-gcc-mips-elf.deb
- sudo dpkg --install --force-overwrite pinguino-linux64-gcc-mips-elf.deb
- sudo apt-get install libcloog-isl4 libisl10
- sudo apt-get install -f
git:
  depth: 500
script:
- ./nuttx/tools/autobuild.sh
- zip -r Buildlogs.zip travis_output > /dev/null
env:
  - BUILDJOBS=3 BUILDJOBID=a
  - BUILDJOBS=3 BUILDJOBID=b
  - BUILDJOBS=3 BUILDJOBID=c
addons:
  artifacts:
    paths:
    - "Buildlogs.zip"
    key:
      secure: zUntHUl8Ji8ZHOehfrXX8vVM9YQbacYHRIodIMc2XKqwbtHHvEFypvq7WVM9glF9RRsbawpD/qwgvmmc7Fq1g5lBD7VIKJPiWSIud/BDiFJiMP0RTjpo7+aBx1cZJjORy1bnrZ0EHtj9R6q7O9PCGwLdGVc8yTgqHVLVe1FN4y4=
    secret:
      secure: mUN6YYgCmVZCbmTvRFX+t9dJl86yg2bMc6Sl1DzEiV/wXChIcg+dLracyc3XMorNSxOKJanjxVdUAw/kt4FiYsONTCN5jJm6BjwMUrS3IcIVWkwW4QwDqw02O3XQ5IgUANpbFxogARKQgi78HFUGy2xoF1xy35Wrn3Ffob4DkiE=
    bucket: nuttx-travis
notifications:
  email:
    - david_s5@usa.net
